### ISSUE TITLE
Incorrect names of artifacts 

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk-distribution#18]
Artifacts has incorrect [names](https://github.com/esrlabs/chipmunk/releases) (for version 3.10.4 was used 3.10.3). Probably hardcoded 

![image](https://github.com/esrlabs/chipmunk-distribution/assets/12843747/64322be6-ba76-4d4d-8fe2-43041f3adccc)

Also would be nice to have all names in the same pattern
```
chipmunk@TAG-linux-x86_64.EXT

ex:
chipmunk@3.10.4-linux-x86_64.rpm
chipmunk@3.10.4-linux-x86_64.deb
```

**Comment by itsmesamster** [comment]
Resolved the issue for rpm file.
